# Generated by Django 4.2.1 on 2023-08-09 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APItest', '0002_person_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='skill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_skill', to='APItest.person_skill'),
        ),
    ]
